### ISSUE TITLE
Deprecating Facebook Login support on Android WebViews and Facebook SDK =>8.2.0

### ISSUE THREAD

**Issue by dodocss** [CrossGeeks/FacebookClientPlugin#101]
There are some breaking changes going on on Facebook side.

1. Facebook Login will no longer support using Android embedded browsers (WebViews) for logging in users
2. Ensure your app is using version 8.2.0 or later of the Facebook SDK for Android

As this library has dependencies to Facebook.Android components ( https://github.com/xamarin/FacebookComponents/tree/main/Facebook.Android ), it's worth mentioning that there is a work going on related with update to the latest Facebook SDK: https://github.com/xamarin/FacebookComponents/pull/214

Can we expect, that the plugin will be updated accordingly, before the final deprecation before 5.10.2021?

**Comment by angelru** [comment]
It seems that the plugin is no longer maintained, you have to go to the implementation of each platform

**Comment by dodocss** [comment]
Just the update from dependent library: https://github.com/xamarin/FacebookComponents/releases/tag/FacebookAndroid-20211019
Xamarin.Facebook.Android v11.2 is here.
Can we expect that this library will be updated accordingly?

**Comment by rdelrosario** [comment]
New version released!

**Comment by dodocss** [comment]
Thanks a lot @rdelrosario !
