### ISSUE TITLE
Plugin crash when app already exists

### ISSUE THREAD

**Issue by sayed-seliman** [CrossGeeks/FacebookClientPlugin#11]
Hi,

when Facebook app (on the profile settings of Facebook) already exists and I try to log again, lot of time but not always, the plugin crash.

I have to manually remove app from my Facebook profile page and everythings start to work again.

**Comment by rdelrosario** [comment]
Hey

Do you have the stacktrace?

**Comment by rdelrosario** [comment]
On which platform iOS or Android?

**Comment by rdelrosario** [comment]
Try the latest version, if still occurring feel free to reopen it or open a new issue. I might need at least the stack trace if does happen again.
