### ISSUE TITLE
Any suggestions for the deprecated publish actions of facebook?

### ISSUE THREAD

**Issue by zalavaz1101** [CrossGeeks/FacebookClientPlugin#25]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by rdelrosario** [comment]
My understanding is that what was deprecated is the custom open graph stories. Facebook suggest what to do instead here:

https://developers.facebook.com/docs/sharing/opengraph/custom-open-graph-deprecation

**Comment by rdelrosario** [comment]
Use built-in Open Graph actions, including the new games.plays, which posts only to people's activity log, and books.rates.
Or use standard link, quote, photo, video, or multi-media share.

**Comment by zalavaz1101** [comment]
Thanks for the reply.

I mean, in your tutorial is stated that you need the publish actions
permission in order to use the plugin (I only use standard text and image
share as stated in the tutorials). But as you know, this permission Is been
deprecated right now (I know because my application was rejected in the
review) and I about to release my App to the public. Do you know what other
permission do I need to request from Facebook to make the sharing work? or
the plugin will never work with the current Facebook policies?.

Thanks in advance. Regards

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Tue, Jul 10, 2018 at 5:10 PM, Rendy Del Rosario <notifications@github.com
