### ISSUE TITLE
sample plist keychain-access-groups comes from where?

### ISSUE THREAD

**Issue by bda2206** [CrossGeeks/FacebookClientPlugin#26]
Hello Crossgeeks, and thanks for the plugins :)

looking at your sample plist, where/what  does the line

<string>com.fbc.example.facebookclientsample</string>

come from or reference? Its different to the bundle identifier of your app.

regards

Brian

**Comment by rdelrosario** [comment]
Just fixed it should be the same on both. Thanks for finding this.

**Comment by rdelrosario** [comment]
This is necessary for facebook login to work on iOS physical devices.
