### ISSUE TITLE
CrossFacebookClient.Current.IsLoggedIn always false after closed the app on iOS

### ISSUE THREAD

**Issue by sayed-seliman** [CrossGeeks/FacebookClientPlugin#3]
Hi,

on iOS if I just close the app (without logout) the CrossFacebookClient.Current.IsLoggedIn is FALSE and CrossFacebookClient.Current.ActiveToken is EMPTY so I cannot make an "auto login" to the user.

On Android the same code works perfectly

**Comment by rdelrosario** [comment]
I think I found a possible fix:

https://coffeeshopped.com/2011/01/saving-sessions-with-the-facebook-ios-sdk

Will find sometime to implement this

**Comment by sayed-seliman** [comment]
Hi,

any news about this problem?

Thanks

**Comment by rdelrosario** [comment]
This might be fixed on:

https://www.nuget.org/packages/Plugin.FacebookClient/1.1.0-rc1

**Comment by rdelrosario** [comment]
Should be fixed on version 1.1.0:

https://www.nuget.org/packages/Plugin.FacebookClient/1.1.0
