### ISSUE TITLE
(#200) Requires extended permission: publish_actions

### ISSUE THREAD

**Issue by Yashshree** [CrossGeeks/FacebookClientPlugin#30]
I am trying to share via facebook account which is added as a tester. plus i am unable to see public_action as permission. please help.

**Comment by rdelrosario** [comment]
On latest version doesn't use this permission since it was deprecated, now uses sharing dialogs which doesn't require them.

For more information:

https://developers.facebook.com/docs/sharing/android/
https://developers.facebook.com/docs/sharing/ios/

**Comment by Yashshree** [comment]
How to open sharing dialog using this plugin?

**Comment by rdelrosario** [comment]
Is on the docs by using the SharingAsync method

**Comment by Yashshree** [comment]
I am using that same method hence i am getting Requires extended permission: publish_actions
