### ISSUE TITLE
issue with permissions publish_actions deprecated now

### ISSUE THREAD

**Issue by kumarDev83** [CrossGeeks/FacebookClientPlugin#32]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.4.0
Device Tested On: 03-08-2018
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 
Versions of other things you are using:

### Steps to reproduce the Behavior
Try to share a photo and it will complain about deprecated actions. The issue is we can't specify permissions while sharing whereas while logging in we can.
### Code snippet
FacebookSharePhotoContent photoContent = new FacebookSharePhotoContent(photos.ToArray());
                var ret = await CrossFacebookClient.Current.ShareAsync(photoContent);

**Comment by rdelrosario** [comment]
How are you doing the login?

You cannot request publish_actions this permission was deprecated.

**Comment by kumarDev83** [comment]
I had to change login from what has been given in documentation.
 string[] permisions = new string[] { "manage_pages", "publish_pages" };
await CrossFacebookClient.Current.LoginAsync(permisions,FacebookPermissionType.Publish);
This works fine now. 

From the documentation, this won't work for me as you can't ask read permissions while sending permission type of publish.
 await CrossFacebookClient.Current.LoginAsync( new string[] {"user_friends"},FacebookPermissionType.Publish);
