### ISSUE TITLE
Facebook SDK not initializing.

### ISSUE THREAD

**Issue by VikasPawar2112** [CrossGeeks/FacebookClientPlugin#36]
ISSUE : I am using Facebook plugin in my xamrin project, and it's giving me following exception.

Plugin Version : v1.4.0.

Exception : Unhandled Exception:

Xamarin.Facebook.FacebookSdkNotInitializedException: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.

Code Snippet : 
1. MainActivity.cs - i. onCreate()
`  base.OnCreate(bundle);
            FacebookClientManager.Initialize(this);`

ii. OnActivityResult()
`
        protected override void OnActivityResult(int requestCode, Result resultCode, Intent intent)
        {
            base.OnActivityResult(requestCode, resultCode, intent);
            FacebookClientManager.OnActivityResult(requestCode, resultCode, intent);
        }`

2. Manifest file :
I have setup everything in the manifest file as show in documentation. 

Can anyone tell me, why i am having this issue? Thank You!

**Comment by Andre-Inklusion** [comment]
I am having the same issue.

Did you find the cause?

**Comment by hjorrip** [comment]
Same issue here

**Comment by rdelrosario** [comment]
Closed since this should be fixed in most recent versions

**Comment by JohnathanJohn** [comment]
Facing the Same Issue. Any solution to this yet?

**Comment by rdelrosario** [comment]
Are you using latest version?

**Comment by Whrothus** [comment]
Had the same problem.
fixed it did not read well

AndroidManifest.xml
"Also define this within the application tag"

Did not do that in the tags
Hope this helps
