### ISSUE TITLE
Cannot share link content with quote

### ISSUE THREAD

**Issue by Yashshree** [CrossGeeks/FacebookClientPlugin#37]
This is my code. 

Plugin.FacebookClient.Abstractions.FacebookShareLinkContent linkContent = new Plugin.FacebookClient.Abstractions.FacebookShareLinkContent("awesome plugins",new Uri("http://www.github.com/crossgeeks", UriKind.Absolute));
                    var ret =await  CrossFacebookClient.Current.ShareAsync(linkContent);

i am getting error as 
Cannot share link content with quote

**Comment by rdelrosario** [comment]
Tested on iOS and Android on latest version and is working fine. Please re-open with more details if still not.
