### ISSUE TITLE
Could not initialize   (FacebookClientManager.Initialize(this);) in xamarin android?

### ISSUE THREAD

**Issue by RagulChandra** [CrossGeeks/FacebookClientPlugin#38]
## Bug Information

Version Number of Plugin: 1.4.0
Device Tested On:
Simulator Tested On:
Version of VS: 7.4.2
Version of Xamarin:1.6.1
Versions of other things you are using: Android 8.1

**Comment by mindport** [comment]
Got the same issue

**Comment by rdelrosario** [comment]
Closing since this should be fixed in most recent versions.
