### ISSUE TITLE
[Android] Parameters in graph request not working

### ISSUE THREAD

**Issue by TimotejRybar** [CrossGeeks/FacebookClientPlugin#4]
Hi, thank you for this easy to use wonderful library.

I've encountered problem when calling graph request

`            await CrossFacebookClient.Current.QueryDataAsync("me/friends", new string[] { "user_friends" }, new Dictionary<string, string>()
            {
                {"fields" , "email"}
            });`

`System.Collections.Generic.KeyNotFoundException: <Timeout exceeded getting exception details>`

I've tried other graph calls without parameters and they worked like charm.

Am i doing anything wrong? Login works successfully too.

**Comment by rdelrosario** [comment]
Hi

Do you have the complete stack trace? that might be helpful

**Comment by TimotejRybar** [comment]
Hi rdelrosario, thank you for quick response

I'm not sure if i copied stack trace correctly, this is my first time resolving issue on github.

Here it is

`01-28 15:27:53.728 I/MonoDroid(31351): UNHANDLED EXCEPTION:
01-28 15:27:53.771 I/MonoDroid(31351): System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
01-28 15:27:53.771 I/MonoDroid(31351):   at System.Collections.Generic.Dictionary 2[TKey,TValue].get_Item (TKey key) [0x0001e] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-28 15:27:53.771 I/MonoDroid(31351):   at Plugin.FacebookClient.FacebookClientManager+<RequestData>d__65.MoveNext () [0x0018b] in C:\Plugins\FacebookClient\src\Plugin.FacebookClient.Android\FacebookClientManager.cs:477 
01-28 15:27:53.771 I/MonoDroid(31351): --- End of stack trace from previous location where exception was thrown ---
01-28 15:27:53.771 I/MonoDroid(31351):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-28 15:27:53.772 I/MonoDroid(31351):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-28 15:27:53.772 I/MonoDroid(31351):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <8211f1f12f9e45838d631abf63e51c79>:0 
01-28 15:27:53.772 I/MonoDroid(31351):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <8211f1f12f9e45838d631abf63e51c79>:0 
01-28 15:27:53.772 I/MonoDroid(31351):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <8211f1f12f9e45838d631abf63e51c79>:0 
01-28 15:27:53.772 I/MonoDroid(31351):   at (wrapper dynamic-method) System.Object:0c6ef2d5-3d31-490d-8b0c-2940c5c73ac6 (intptr,intptr)`

**Comment by rdelrosario** [comment]
Ok try this hotfix :) and let me know:

https://www.nuget.org/packages/Plugin.FacebookClient/1.0.1

**Comment by TimotejRybar** [comment]
Thank you very much, after updating nuget package and rebuilding solution it works perfectly.

Have a nice day :)
