### ISSUE TITLE
[Android] Question: App Signing

### ISSUE THREAD

**Issue by stesvis** [CrossGeeks/FacebookClientPlugin#40]
Hello,

I am sorry I have a problem with step #4 here:
https://github.com/CrossGeeks/FacebookClientPlugin/blob/master/docs/FacebookPortalSetup.md

I generated the hash using the keystore I use to publish the app (the upload certificate).
And it works great when I run the app from VS.
But once published, I get the facebook error message:
![image](https://user-images.githubusercontent.com/6062684/52524189-a85db080-2c57-11e9-8cef-50c4baf21efb.png)

In my facebook app settings I don't have that hash key that they mention:
![image](https://user-images.githubusercontent.com/6062684/52524261-641ee000-2c58-11e9-9b8c-176743cc41e2.png)

Any ideas why it would fail?

I copied that key hash in the error message and added it to the fb settings, and it fixed it, but I still don't understand how this works. Shouldn't I be able to generate it?

**Comment by rdelrosario** [comment]
It failed because the application was signed with a different keystore. Every keystore generates a different hash.

**Comment by dw4rr** [comment]
> It failed because the application was signed with a different keystore. Every keystore generates a different hash.

Is there a solution?
