### ISSUE TITLE
Facebook Mail

### ISSUE THREAD

**Issue by omersezer** [CrossGeeks/FacebookClientPlugin#43]
Hello,

We used this plugin and received mail from facebook.

As a reminder, your app is currently in violation of Facebook Platform Policy 8.2: Native Android apps that implement Facebook Login must use our official SDKs for Login.Please see the screenshot enclosed below.

Please make sure your app is using the most recent version of our SDK for Login. You can find more information on our SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login.

As a reminder, your Android app is currently in violation of Facebook Platform Policy 8.3: Use a clearly branded "Login with Facebook" button and follow the Facebook Brand Guidelines: https://www.facebookbrand.com/.

Your Login button doesn't properly reference Facebook. To fix this issue, you should always use our official SDK for Login. For more information on Login best practices, check out the Login section of our developer documents: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign.

Please respond directly to this email after you have updated your app and we will do our best to assist you.

**Comment by rdelrosario** [comment]
Hi,

I think the problem here is how your button visually looks you need to follow Facebook brand guidelines.
