### ISSUE TITLE
Can't resolve the reference 'System.Void Facebook.ShareKit.ShareVideoContent'

### ISSUE THREAD

**Issue by JavierMoraCasas** [CrossGeeks/FacebookClientPlugin#46]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.6.0
Device Tested On: None
Simulator Tested On: None 
Version of VS: VS Community 8.1.3 (build 19)
Version of Xamarin: 4.0
Versions of other things you are using:

### Steps to reproduce the Behavior
Add plugin

### Expected Behavior
Compilation OK

### Actual Behavior
Compilation KO

### Code snippet
MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Facebook.ShareKit.ShareVideoContent::set_PreviewPhoto(Facebook.ShareKit.SharePhoto)', referenced from the method 'System.Void Plugin.FacebookClient.FacebookClientManager::RequestShare(System.Collections.Generic.Dictionary`2<System.String,System.Object>)' in 'Facebook.ShareKit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101)

### Screenshotst
none

**Comment by JavierMoraCasas** [comment]
Hello, any solution for this problem? I don't know what's happening...

**Comment by JavierMoraCasas** [comment]
Hello, anybody have the same problem? I tried to remove and reinstall the plugin and the result was the same. :-(

**Comment by randyrod** [comment]
Hey @JavierMoraCasas,

I was facing the same issue.

Unfortunately to solve it I had to downgrade Xamarin.Facebook.iOS to 4.40.0

**Comment by JavierMoraCasas** [comment]
It Works!!! 

thank you so much @randyrod!!

**Comment by rdelrosario** [comment]
Should be fixed in:

https://www.nuget.org/packages/Plugin.FacebookClient/2.0.1-beta

This version is still in beta but almost releasing a stable version once all tests are completed.

If not fixed after testing this beta please re-open

**Comment by JavierMoraCasas** [comment]
It works also, i'm going to update to 2.0.1-beta. 

Thanks!
