### ISSUE TITLE
Error resolve  'System.Void Facebook.ShareKit.ShareVideoContent'

### ISSUE THREAD

**Issue by MRomeror** [CrossGeeks/FacebookClientPlugin#47]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.6.0
Device Tested On:
Simulator Tested On:
Version of VS: Visual Studio for Mac 8.1.5
Version of Xamarin: 4.0.0.540366
Versions of other things you are using:

### Steps to reproduce the Behavior
Install Plugin
### Code snippet
MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Facebook.ShareKit.ShareVideoContent::set_PreviewPhoto(Facebook.ShareKit.SharePhoto)', referenced from the method 'System.Void Plugin.FacebookClient.FacebookClientManager::RequestShare(System.Collections.Generic.Dictionary`2<System.String,System.Object>)' in 'Facebook.ShareKit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101)

**Comment by MRomeror** [comment]
Any solution?

**Comment by randyrod** [comment]
Hey @MRomeror,

I was facing the same issue. 

Unfortunately to solve it I had to downgrade Xamarin.Facebook.iOS to 4.40.0

**Comment by rdelrosario** [comment]
Should be fixed in:

https://www.nuget.org/packages/Plugin.FacebookClient/2.0.1-beta

This version is still in beta but almost releasing a stable version once all tests are completed.

If not fixed after testing this beta please re-open

**Comment by MRomeror** [comment]
Thank you!!
With that version it works correctly
