### ISSUE TITLE
How can I find the facebook profile page with the ID provided by the Plugin?

### ISSUE THREAD

**Issue by luis95gr** [CrossGeeks/FacebookClientPlugin#48]
## Bug Information

I want to look for facebook profile  some way, I tried with the ID that the Plugin recover but it seems like is another typo of ID, any ideas?

Version Number of Plugin: 1.6.0
Device Tested On:
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 3.6
Versions of other things you are using:

**Comment by rdelrosario** [comment]
You might need fb permissions depending on what profile you are requesting.

But request should be la like as follows:

```cs
  await CrossFacebookClient.Current.QueryDataAsync("{profile-id}", new string[]{ "user_friends"}, new Dictionary<string, string>()
   {
      {"fields", "id, first_name, last_name, middle_name, name, email, picture"}
   });
  
```
Where {profile-id} is the id of the profile you are interested in collecting info.
