### ISSUE TITLE
Log in attempt being registered as "Cancelled"

### ISSUE THREAD

**Issue by vinco83** [CrossGeeks/FacebookClientPlugin#49]
If facebook app isn't installed on android device and a webview is used to login, the callback "FacebookActionStatus" check works fine and registers as "Completed".

If facebook app *IS* installed, when clicking "Continue" on the native view, the callback is always registered as "Cancelled".

## Bug Information

Version Number of Plugin: 1.6
Device Tested On: Android device (Moto E6)
Simulator Tested On:
Version of VS: 2019 16.2.2
Version of Xamarin: 4.1 (latest stable release)
Versions of other things you are using:

### Steps to reproduce the Behavior
Install facebook on Android device and click login button to run "_facebookService.RequestUserDataAsync(fields, permissions);".  Click "Continue as 'Name'", and place breakpoint in RequestUserDataAsync delegate callback. Status will be "Cancelled" with a message of "User cancelled facebook operation"

### Expected Behavior
Status will be "Completed"
### Actual Behavior
Status is "Cancelled"
### Screenshots
![Screenshot_20190818-123257](https://user-images.githubusercontent.com/14079021/63227489-2675b380-c1b5-11e9-9432-14963ab09e14.png)

**Comment by vinco83** [comment]
This ended up being an issue with my hash key that I was able to fix, however the plugin is still returning the wrong status. It should be returning an error, instead of cancelled

**Comment by rdelrosario** [comment]
Should be fixed in:

https://www.nuget.org/packages/Plugin.FacebookClient/2.0.1-beta

This version is still in beta but almost releasing a stable version once all tests are completed.

If not fixed after testing this beta please re-open
