### ISSUE TITLE
result.isCancelled=true

### ISSUE THREAD

**Issue by opacitychris** [CrossGeeks/FacebookClientPlugin#50]
## Bug Information

Cannot get login to work anymore.  I hear the problem is from Xamarin needing to update their Facebook SDK to the latest version, which is a bit behind.

Previous code worked fine but upgrading to iOS13 beta GM version is no longer working with all packages updated.

Version Number of Plugin: latest
Device Tested On: iPhone 8 running iOS 13 GM
Simulator Tested On: iPhone 8 running iOS 13 GM
Version of VS:  latest
Version of Xamarin: latest
Versions of other things you are using:

### Steps to reproduce the Behavior
Click login button

### Expected Behavior
be prompted to login via facebook app or browser, handle the result login success/fail etc

### Actual Behavior
result comes back immediately as IsCancelled=true, no login prompts appear via facebook app or browser

**Comment by engramyosama6** [comment]
Yes, Xamarin updated the SDK already we just need to update the NuGet spec to new version
