### ISSUE TITLE
Problem loggin in with facebook with IOS13

### ISSUE THREAD

**Issue by engramyosama6** [CrossGeeks/FacebookClientPlugin#51]
## Bug Information
The facebook login does not work with ios13 not, it works fine with 12 and lower

Version Number of Plugin: 2.0.1
Simulator Tested On: IOS13 simulator

**Comment by peterbersani** [comment]
I am having the same issue.

**Comment by lars-rogalski** [comment]
I have the same problem

**Comment by karlsson-mvm** [comment]
I can confirm this same exact issue.

**Comment by kcrandall** [comment]
I am also seeing this problem 

2019-10-01 17:23:02.701812-0400 Squirb.iOS[1328:19850] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
is the error message. Everything was working in iOS 12
