### ISSUE TITLE
Application fail on ios 13.1.2. FBSDKLog: Unable to find a valid UIWindow

### ISSUE THREAD

**Issue by flatplanetpl** [CrossGeeks/FacebookClientPlugin#54]
## Bug Information

Version Number of Plugin: 2.1.9
Device Tested On: iPhone X, ios: 13.1.2
Simulator Tested On: 
Version of VS: Visual Studio for Mac 8.3.1 (build 18)
Version of Xamarin:  6.2.0.42 

### Steps to reproduce the Behavior
Run application with facebook login.

### Expected Behavior
Application shuld start.

### Actual Behavior
Application run fail. Ends with  error:

> 2019-10-03 00:47:04.197 xx.iOS[1540:653099] FBSDKLog: Unable to find a valid UIWindow

> 
> =================================================================
> 	Native stacktrace:
> =================================================================
> 	0x104b29418 - /private/var/containers/Bundle/Application/90DE6141-4A58-49DA-88E7-02A002F53D95/xx.iOS.app/xx.iOS : (null)
> 	0x104b1f200 - /private/var/containers/Bundle/Application/90DE6141-4A58-49DA-88E7-02A002F53D95/xx.iOS.app/xx.iOS : (null)
> 	0x104b288d8 - /private/var/containers/Bundle/Application/90DE6141-4A58-49DA-88E7-02A002F53D95/xx.iOS.app/xx.iOS : (null)
> 	0x1a39ff894 - /usr/lib/system/libsystem_platform.dylib : <redacted>
> 	0x1a3aebf1c - /usr/lib/system/libsystem_kernel.dylib : <redacted>
> 	0x1a3aebf4c - /usr/lib/system/libsystem_kernel.dylib : <redacted>
> 	0x1a9df2cc8 - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
> 	0x1a9df2c08 - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
> 	0x1a9df6b28 - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
> 	0x1a38c9d88 - /usr/lib/system/libxpc.dylib : <redacted>
> 	0x1a38be01c - /usr/lib/system/libxpc.dylib : <redacted>
> 	0x1a39be204 - /usr/lib/system/libdispatch.dylib : <redacted>
> 	0x1a3994d1c - /usr/lib/system/libdispatch.dylib : <redacted>
> 	0x1a39a4d94 - /usr/lib/system/libdispatch.dylib : <redacted>
> 	0x1a3a0dfdc - /usr/lib/system/libsystem_pthread.dylib : _pthread_wqthread
> 	0x1a3a10ae0 - /usr/lib/system/libsystem_pthread.dylib : start_wqthread
> 
> =================================================================
> 	Basic Fault Address Reporting
> =================================================================
> Memory around native instruction pointer (0x1a3ae7928):0x1a3ae7918  c0 03 5f d6 c0 03 5f d6 30 41 80 d2 01 10 00 d4  .._..._.0A......
> 0x1a3ae7928  e3 00 00 54 fd 7b bf a9 fd 03 00 91 7c 81 ff 97  ...T.{......|...
> 0x1a3ae7938  bf 03 00 91 fd 7b c1 a8 c0 03 5f d6 c0 03 5f d6  .....{...._..._.
> 0x1a3ae7948  d0 03 80 d2 01 10 00 d4 e3 00 00 54 fd 7b bf a9  ...........T.{..

**Comment by rdelrosario** [comment]
Just uploaded a new version that should fix this.

**Comment by flatplanetpl** [comment]
Simulator on 13.1 works fine but device still fail.

**Comment by kcrandall** [comment]
@flatplanetpl I have found the same thing and opened an issue

**Comment by kcrandall** [comment]
@flatplanetpl 
https://github.com/CrossGeeks/FacebookClientPlugin/issues/55, adding keychain fixed it for me

**Comment by pedrovelmo** [comment]
Has this been solved? Having the same issue
