### ISSUE TITLE
Fail to launch using 2.1.14 on an iPhone 11 Pro Device iOS 13.1.2

### ISSUE THREAD

**Issue by kcrandall** [CrossGeeks/FacebookClientPlugin#55]
#30  Bug Information

Version Number of Plugin: 2.1.14
Device Tested On: iPhone 11 Pro
Simulator Tested On: On Device
Version of VS: 8.3.1 Build 18
Version of Xamarin: 6.2
Versions of other things you are using:

### Steps to reproduce the Behavior
Attempt to launch facebook login flow. 
### Expected Behavior
Alert pops up from facebook asking to continue
### Actual Behavior
Nothing pops up.
### Further explanation:
I have it working on a simulator running iOS 13.0 with 2.1.9 and 2.1.14. I previously had it working on an iPhone XS device and simulator running plugin version 1.6 and iOS 12. The previous 2.1.X builds (and current build on iOS 13.0) always produce outputs to the console with an -openurl facebook error. Prior to 2.1.9 facebook login would fail to launch and now, with 2.1.9 and 2.1.14, it works on an iPhone 11 simulator running 13.0, but not on an iPhone 11 Pro Device with 13.1 or 13.1.2 (I upgraded to see if it was just 13.1).
 
The weirdest thing is that it's not crashing or producing any errors/outputs, it's just not doing anything on the 13.1.2 iPhone 11 Pro device.

### Code snippet
```
var result = await Plugin.FacebookClient.CrossFacebookClient.Current.
                    RequestUserDataAsync(
                       new string[] { "email", "first_name", "last_name" },
                           new string[] { "email", "public_profile" });
```

**Comment by rdelrosario** [comment]
Did you enable keychain on your Entitlements.plist file?

**Comment by kcrandall** [comment]
Nope, that seemed to be the problem. After adding {team-id}.{bundle-id}, the problem fixed itself.
