### ISSUE TITLE
Package Plugin.FacebookClient 2.1.14 is not compatible with portable45-net45+win8+wpa81

### ISSUE THREAD

**Issue by myonlinegolfclub** [CrossGeeks/FacebookClientPlugin#56]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.1.14
Device Tested On: N/A
Simulator Tested On: N/A
Version of VS: MAC 2019
Version of Xamarin: 4.2
Versions of other things you are using: N/A

### Steps to reproduce the Behavior
Updating package error:

### Expected Behavior
Should update

### Actual Behavior
Package Plugin.FacebookClient 2.1.14 is not compatible with portable45-net45+win8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile111). Package Plugin.FacebookClient 2.1.14 supports:
  - monoandroid81 (MonoAndroid,Version=v8.1)
  - monoandroid90 (MonoAndroid,Version=v9.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

**Comment by rdelrosario** [comment]
This version is not compatible with PCL projects just .NETStandard projects.
