### ISSUE TITLE
Apple Submission Rejection possible misuse of Advertising Identifier?

### ISSUE THREAD

**Issue by NehpetsEtnam** [CrossGeeks/FacebookClientPlugin#57]
Version Number of Plugin: 2.1.16-beta
Version of Xamarin: 3.4.0.1039999

When I upgraded the version of this plugin from 1.4.0 to 2.1.16-beta, my app submission was rejected due to IDFA identifier.

Any help how to fix this issue?

**Comment by rdelrosario** [comment]
This doesn't seem to be related to the plugin

**Comment by NehpetsEtnam** [comment]
I'm not sure but originally my app was using version 1.4.0 and no problem with IDFA, I upgraded to version 2.1.16-beta and was tagged as misused IDFA. I downgraded the version back to 1.4.0 and IDFA issue was gone when I submitted the app on apple.
