### ISSUE TITLE
Can this plugin invoke the App Invite Dialog

### ISSUE THREAD

**Issue by Jbonavita** [CrossGeeks/FacebookClientPlugin#6]
Is it possible to invoke the Facebook App Invite Dialog?

Thanks,
Joe

**Comment by rdelrosario** [comment]
Just added support for this try:

https://www.nuget.org/packages/Plugin.FacebookClient/1.1.0-rc

```cs

  await CrossFacebookClient.Current.ShowAppInviteDialog("<APP LINK URL>","<PREVIEW IMAGE URL>");

```

**Comment by Jbonavita** [comment]
Hi @rdelrosario It turns out that Facebook deprecated the App Invite Dialog.
Thanks.

**Comment by rdelrosario** [comment]
mmm maybe old sdk. But doesn't seem to be deprecated the way I implemented it is still on the reference docs of latest SDK.

https://developers.facebook.com/docs/reference/iossdk/current/FBSDKShareKit/classes/fbsdkappinvitecontent.html

**Comment by Jbonavita** [comment]
That's interesting. Everything I found said it was deprecated.


I'll try it out. Thanks.

________________________________
