### ISSUE TITLE
Error after calling CrossFacebookClient.Current.Logout()

### ISSUE THREAD

**Issue by DontBeEvilBen** [CrossGeeks/FacebookClientPlugin#61]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.2.1
Device Tested On: Galaxy Note 9
Simulator Tested On: Galaxy Note 9
Version of VS: 16.2.3
Version of Xamarin: Xamarin.Forms 4.4.0.991477
Versions of other things you are using:

### Steps to reproduce the Behavior
Step 1: Call await CrossFacebookClient.Current.LoginAsync(new string[] { "public_profile", "email" }); to login with Facebook
Step 2: Call CrossFacebookClient.Current.Logout(); to lot out of with Facebook
Step 3: Call await CrossFacebookClient.Current.LoginAsync(new string[] { "public_profile", "email" }); again to login with Facebook again

### Expected Behavior
It should log me back in and get user's profile information from Facebook as it did on step 1. 

### Actual Behavior
NullReferenceException happens.
Details:
System.NullReferenceException
  Message=Object reference not set to an instance of an object.

Note that CrossFacebookClient.Current is NOT null. So something in the LoginAsync() is using a null object.

**Comment by rdelrosario** [comment]
Can you post the full stacktrace?

**Comment by DontBeEvilBen** [comment]
Hello,
This is all I have:
System.NullReferenceException
  Message=Object reference not set to an instance of an object.

I had tried downloading the code from GitHub and added it to my project. But I received the NotImplementedException error.
How do I get you the full stacktrace?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rdelrosario** [comment]
Can you reproduce this in the sample project?

**Comment by DontBeEvilBen** [comment]
Hello,
No. The sample project works very well. I can log in and out with no issues.
I will see what are the differences between my project and the sample one.

Thank you.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by DontBeEvilBen** [comment]
From what I can tell, the only difference is that I call the Facebook graph API to get the user data instead of using "await CrossFacebookClient.Current.RequestUserDataAsync" as the Sample Project does. 
Any idea what is null??? 
I did try to remove the app from facebook and log in again. The result is the same.

**Comment by DontBeEvilBen** [comment]
I got it to work... 
I missed a couple of things on the android project. I followed the steps in this article and things are working now!!! 
https://www.xamboy.com/2018/03/26/facebook-client-plugin-for-xamarin/
