### ISSUE TITLE
Cannot find FacebookClientManager.Initialize(this) for Xamarin Android

### ISSUE THREAD

**Issue by nabilakhlaque** [CrossGeeks/FacebookClientPlugin#62]
Hello, Im using version 2.2.1. I have installed it in all my projects. I have no issue Initializing it in iOS, but I cannot find it in Android-project. And Iäm compile using Android version (Target Framework): Android 8.1 Oreo

using Plugin.FacebookClient;

FacebookClientManager.Initialize(this);

**Error: The name 'FacebookClientManager' does not exist in the current contect...**

**Comment by rdelrosario** [comment]
This plugin needs to be compiled using Target Framework : Android 9.0+
