### ISSUE TITLE
Not able to login with new App_Name and App_ID using sample app.

### ISSUE THREAD

**Issue by Sumit2668** [CrossGeeks/FacebookClientPlugin#68]
Hi Guys,

I try your sample app and I am successfully able to login to Facebook. But when I try to update my APP_ID and APP_Name inside Strings.xml file I got an error during login. I debug a lot but didn't get any clue. I am struggling with this issue on Android.

See the screenshot attached 
![screenshot-1586367897530](https://user-images.githubusercontent.com/26775231/78816132-e89cf800-79ee-11ea-8516-0350855ed3a0.jpg)
Please Help Me 
Thanks in advance

**Comment by Zolispurs7** [comment]
You have to insert your computer hash code, on the facebook developer site.
If you try this code on a android 9 phone, this error message will be contains the hash, that you have to insert on the developer site.

**Comment by conor-codes** [comment]
I'm getting the same, i've updated my hash on facebook developer and on android 10 i get the same login error. If i try android 9 I get "Login Failed. Sorry, unable to login. Please check your internet connection". 

But it still returns the facebook information which is odd.

**Comment by Sumit2668** [comment]
@conor-codes , i think you generate wrong hash key so please use  **openssl-0.9.8e_X64** then you generate new key then try again.
https://code.google.com/archive/p/openssl-for-windows/downloads
