### ISSUE TITLE
AppInvite for Android throwing MissingMethodException

### ISSUE THREAD

**Issue by Jbonavita** [CrossGeeks/FacebookClientPlugin#7]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.1.0-rc1
Device Tested On: Android
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 
Versions of other things you are using:

### Steps to reproduce the Behavior
Add Plugin.FacebookClient to both the PCL and Android projects. 
Subscribe to the OnAppInvite event
Call the ShowAppInviteDialog method
                
### Expected Behavior

I expected the App Invite dialog to display.

### Actual Behavior
    Unhandled Exception:

    System.MissingMethodException: Method 
    'Plugin.FacebookClient.Abstractions.IFacebookClient.add_OnAppInvite' not found. occurred
### Code snippet
    
    Plugin.FacebookClient.CrossFacebookClient.Current.OnAppInvite += Current_OnAppInvite;
     await Plugin.FacebookClient.CrossFacebookClient.Current.ShowAppInviteDialog("our app link url", "our url");

        private void Current_OnAppInvite(object sender, Plugin.FacebookClient.Abstractions.FBEventArgs<Dictionary<string, object>> e)
        {
            
        }

In the Android project I added the following to the MainActivity.cs

    FacebookClientManager.Initialize(this);

        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            FacebookClientManager.OnActivityResult(requestCode, resultCode, data);
        }

**Comment by Jbonavita** [comment]
I did a clean and full rebuild of the Android project and that seemed to have fixed this one issue.
Now I'm getting "Dialog failed with unknown error" for the Message in the OnAppInvite.

**Comment by rdelrosario** [comment]
I thought they were still supporting this but seems not, so will drop the support for this on the plugin.

https://stackoverflow.com/questions/48144834/dialog-failed-with-unknown-error-response-facebook-app-invite-on-switch-of
