### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by fap0702** [CrossGeeks/FacebookClientPlugin#71]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.2.1
Device Tested On: Samsung A10
Simulator Tested On: 
Version of VS: 8.5.5 (mac)
Version of Xamarin: 4.6.0.726
Versions of other things you are using: Facebook (269.0.0.50.127) - (installed on the device)

### Steps to reproduce the Behavior
I try to log in from my app developed using:

await CrossFacebookClient.Current.RequestUserDataAsync(...)

and it never comes to this event:

CrossFacebookClient.Current.OnUserData += ...

### Expected Behavior
get to this event

CrossFacebookClient.Current.OnUserData 

with the following status:

FacebookActionStatus.Completed: 

### Actual Behavior
I understand that it opens the Facebook app and shows me a red message indicating "Error starting session"

### Code snippet
CrossFacebookClient.Current.OnUserData += (s, a) =>
            {
                FacebookUser fbUser = null;

                switch (a.Status)
                {
                    case FacebookActionStatus.Completed:
                        JObject fbProfile = JObject.Parse(a.Data);
                        fbUser = new FacebookUser
                        {
                            Id = fbProfile["id"].ToString(),
                            FirstName = fbProfile["first_name"].ToString(),
                            LastName = fbProfile["last_name"].ToString(),
                            Email = fbProfile["email"].ToString(),
                            Picture = fbProfile["picture"]["data"]["url"].ToString()
                        };

                        break;
                }

                callMethod(fbUser);
            };
            //await CrossFacebookClient.Current.LoginAsync(new string[] { "email" });
            await CrossFacebookClient.Current.RequestUserDataAsync(new string[] { "email", "first_name", "gender", "last_name", "birthday", "picture" }, new string[] { "email" });

### Observation
I have noticed that if I deactivate or uninstall the facebook app it shows me the login in browser mode and I can log in successfully. there is some way to force the plugin to always use the web environment and not to use the installed app for the login

### Screenshotst
![Screenshot_20200513-121136](https://user-images.githubusercontent.com/16230373/81844071-28865c00-9514-11ea-88bd-ff2793927a1b.jpg)

**Comment by rdelrosario** [comment]
It seems you are missing Facebook portal configuration

**Comment by jrthurler** [comment]
I'm having the same issue! If I logout from Facebook App and try to login again from my app, I can log in successfully, but sometimes I receive the same message displayed above.

**Comment by jrthurler** [comment]
This is my code used to login: 

[var fbLoginResponse = await CrossFacebookClient.Current.LoginAsync(new string[] { "email", "public_profile" });](url)

**Comment by jrthurler** [comment]
![FB Error](https://user-images.githubusercontent.com/8081194/82578681-b5f02e80-9b5a-11ea-8eed-27766d6e9e7f.jpg)

**Comment by fap0702** [comment]
I managed to solve it, I don't know exactly what the solution was but what I did was the following:

- enter android data again in facebook settings

- add again all the keyhash that it generated for debug and release mode

Thank you!
