### ISSUE TITLE
Post to facebook GraphApi

### ISSUE THREAD

**Issue by werddomain** [CrossGeeks/FacebookClientPlugin#72]
## Bug Information
Can't post to GraphAPI. [Your blog post](https://www.xamboy.com/2018/03/26/facebook-client-plugin-for-xamarin/) say to use **await CrossFacebookClient.Current.PostDataAsync** but it's not found.

Version Number of Plugin: 2.2.1
Device Tested On:
Simulator Tested On:
Version of VS: 2019
Version of Xamarin: 28.0.0.3
Versions of other things you are using: xarmin.forms 4.4.0.991265+398-sha.ee1eca51d-azdo.3306453

### Screenshotst
CrossFacebookClient.Current.PostDataAsync

**Comment by rdelrosario** [comment]
Just updated the article since this method was deprecated because Facebook deprecated the ability to post by using graph api.
