### ISSUE TITLE
An Aside about MVVM

### ISSUE THREAD

**Issue by MickCG** [CrossGeeks/FacebookClientPlugin#73]
I have an app that is going to use Facebook as my authentication, Xamarin. I have tried several different techniques for logging on. This seemed the most straight forward. As a first step, I got the example code running, which worked like a champ. Next, I tried to get the same code working in my starter app, I am not real familiar with the MVVM use frankly, understand it basically, but not the details. Here is the problem. I know I am logging on, I know I'm pulling the email, Full Name but after those are pulled the fields are not displayed on the LoginPage? Anyone have an idea what I could look for? Man it sure looks the same to me with just name changes for my solution name.

**Comment by rdelrosario** [comment]
This issue doesn't seem to be related to this plugin.
