### ISSUE TITLE
Android: Share doesn't return and doesn't call OnSharing if postId is null

### ISSUE THREAD

**Issue by NGumby** [CrossGeeks/FacebookClientPlugin#82]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

On Android, When sharing to Only Me (not sure if it repros with public post), the call to 

var result = await CrossFacebookClient.Current.ShareAsync(shareContent);

never returns and OnSharing is not called.  Looking at the code it's obvious that it doesn't work if PostId is null (which seems to be a common issue).  I have a pull request coming up to fix it.

Version Number of Plugin: 2.2.1
Device Tested On: Huawei Mate 20 Pro
Simulator Tested On:
Version of VS: 16.7.3
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

Share a post to Only me, OnSharing is never called

### Expected Behavior

OnSharing to be called

**Comment by DeanZhuo** [comment]
This issue still happens on version 2.2.1. Please help.
