### ISSUE TITLE
Loging in with facebook on Parse platform Server

### ISSUE THREAD

**Issue by CDrosos** [CrossGeeks/FacebookClientPlugin#9]
Hello,
I would like to use this plugin to login my users on a parse server.

Now the best way in our days to login on Parse was something that is described here: https://stackoverflow.com/questions/40529682/making-a-prettier-facebook-login-screen-for-parse-com-server-with-xamarin-androi

which pretty much what it says is that after you do a native facebook login, with the return data you do something like this to login on Parse:

```
public async void OnSuccess(Object result)
    {
        // We know that this is a LoginResult
        var loginResult = (LoginResult) result;

        // Convert Java.Util.Date to DateTime
        var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var expireDate = epoch.AddMilliseconds(loginResult.AccessToken.Expires.Time);

        // FB User AccessToken
        var accessToken = loginResult.AccessToken.Token;

        ParseUser user = await ParseFacebookUtils.LogInAsync("Your Facebook App Id", accessToken, expireDate);
    }
```

But how i can get **AccessToken** and **expireDate** with your plugin?
Thanks

**Comment by CDrosos** [comment]
@rdelrosario @Pujolsluis please assist :) :)

**Comment by Pujolsluis** [comment]
Hey @CDrosos ,
I'm glad you're looking forward to using the plugin! :D, thank you for submitting this issue. we will be working on it to enable the required properties.

**Comment by rdelrosario** [comment]
@CDrosos  Just released a new version:

https://www.nuget.org/packages/Plugin.FacebookClient/1.1.0

Should be able to access token:
```cs
CrossFacebookClient.Current.ActiveToken
```

And expiration date as well:
```cs
CrossFacebookClient.Current.TokenExpirationDate
```

**Comment by rdelrosario** [comment]
Available on latest version

https://www.nuget.org/packages/Plugin.FacebookClient/1.2.0

**Comment by stesvis** [comment]
@rdelrosario would it be possible to also provide a property for the **AuthorizationCode** as well?
https://developers.facebook.com/docs/accountkit/accesstokens/#authcode

I am consuming some APIs that required the code instead of the **ActiveToken**.
